name: Deploy to FTP

# Déclencheur : à chaque push sur la branche master
on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    name: Deploy FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site
        run: hugo --minify

      - name: Liste des fichiers dans le dossier public
        run: ls -lR public/

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_BU }}
          username: ${{ secrets.FTP_USERNAME_BU }}
          password: ${{ secrets.FTP_PASSWORD_BU }}
          server-dir: /nathanswiss/
          local-dir: public/

  pushover-actions:
    name: send pushover push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: pushover-actions
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_APITOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USERNAME }}
        with:
          status: ${{ job.status }}
          title: 'Github Repo nathan.swiss'
          message: 'Le site a été mis à jour'
          url: 'https://nathan.swiss'
